[package]
name = "vultan"
version = "0.1.0"
edition = "2021"
authors = ["Pierre Chanquion <{FORENAME}.{FIRST_FIVE_LETTERS_OF_SURNAME}.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
mockall = "0.11"
rand = "0.8.5"
regex = "1"
ron = "0.8"
serde = { version = "1", features = ["derive"] }
